# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default title', max_length=200)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description_json', models.BinaryField(default='')),
                ('storage_path', models.CharField(default='', max_length=200)),
                ('storage_name', models.CharField(default='', max_length=200)),
                ('source_path', models.CharField(default='', max_length=200)),
                ('preview_storage_path', models.CharField(default='', max_length=200)),
                ('preview_storage_name', models.CharField(default='', max_length=200)),
                ('video_width', models.CharField(default='300', max_length=200)),
                ('video_height', models.CharField(default='300', max_length=200)),
                ('video_size', models.CharField(default='0', max_length=200)),
                ('video_size_str', models.CharField(default='0', max_length=200)),
                ('video_duration_str', models.CharField(default='0', max_length=200)),
                ('video_status', models.CharField(choices=[('Video is downloading', 'Downloading'), ('Video is downloaded', 'Downloaded'), ('Video status not set', 'Notset')], default='Video status not set', max_length=200)),
            ],
        ),
    ]
