# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bot_status', models.CharField(choices=[('Bot is working', 'Working'), ('Bot is finishing', 'Finishing'), ('Bot is stopped', 'Stopped')], default='Bot is stopped', max_length=200)),
                ('bot_task', models.CharField(choices=[('Download webms from 2ch', 'Download'), ('Remove webms', 'Remove')], default='Download webms from 2ch', max_length=200)),
                ('task_data', models.BinaryField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='PaginatorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paginator_json', models.BinaryField(default='')),
                ('category', models.CharField(choices=[('Hot category', 'hot'), ('Adult category', 'adult'), ('Webm category', 'webm'), ('Mp4 category', 'mp4'), ('Category notset', 'notset')], default='Category notset', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default title', max_length=200)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description_json', models.BinaryField(default=b'')),
                ('storage_path', models.CharField(default='', max_length=200)),
                ('storage_name', models.CharField(default='', max_length=200)),
                ('storage_path_url', models.CharField(default='', max_length=200)),
                ('source_path', models.CharField(default='', max_length=200)),
                ('source_thread_number', models.CharField(default='', max_length=200)),
                ('source_thread_path', models.CharField(default='', max_length=200)),
                ('preview_storage_path', models.CharField(default='', max_length=200)),
                ('preview_storage_name', models.CharField(default='', max_length=200)),
                ('preview_storage_path_url', models.CharField(default='', max_length=200)),
                ('video_width', models.CharField(default='300', max_length=200)),
                ('video_height', models.CharField(default='300', max_length=200)),
                ('video_size', models.CharField(default='0', max_length=200)),
                ('video_size_str', models.CharField(default='0', max_length=200)),
                ('video_duration_str', models.CharField(default='0', max_length=200)),
                ('is_adult', models.BooleanField(default=False, max_length=1)),
                ('is_music', models.BooleanField(default=False, max_length=1)),
                ('is_hot', models.BooleanField(default=False, max_length=1)),
                ('is_webm', models.BooleanField(default=False, max_length=1)),
                ('is_mp4', models.BooleanField(default=False, max_length=1)),
                ('is_deleted', models.BooleanField(default=False, max_length=1)),
                ('is_source_object_deleted', models.BooleanField(default=False, max_length=1)),
                ('is_source_thread_deleted', models.BooleanField(default=False, max_length=1)),
                ('video_status', models.CharField(choices=[('Video is downloading', 'Downloading'), ('Video is downloaded', 'Downloaded'), ('Video status not set', 'Notset'), ('Video status error', 'Error'), ('Video is hidden', 'Hidden'), ('Video is deleted', 'Deleted')], default='Video status not set', max_length=200)),
                ('video_format', models.CharField(choices=[('.mp4', 'mp4'), ('.webm', 'webm')], default='.webm', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VideoLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VideoViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='video_likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadsource.VideoLikes'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_views',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadsource.VideoViews'),
        ),
    ]
