# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deadsource', '0003_video_is_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bot_status', models.CharField(choices=[('Bot is working', 'Working'), ('Bot is finishing', 'Finishing'), ('Bot is stopped', 'Stopped')], default='Bot is stopped', max_length=200)),
                ('bot_task', models.CharField(choices=[('Download webms from 2ch', 'Download'), ('Remove webms', 'Remove')], default='Download webms from 2ch', max_length=200)),
                ('task_data', models.BinaryField(default='{}')),
            ],
        ),
    ]
