# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadsource', '0006_video_is_webm'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_mp4',
            field=models.BooleanField(default=False, max_length=1),
        ),
    ]
