# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadsource', '0008_auto_20171114_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_thread_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='source_thread_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_status',
            field=models.CharField(choices=[('Video is downloading', 'Downloading'), ('Video is downloaded', 'Downloaded'), ('Video status not set', 'Notset'), ('Video status error', 'Error')], default='Video status not set', max_length=200),
        ),
    ]
