# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadsource', '0010_video_video_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_format',
            field=models.CharField(choices=[('.mp4', 'mp4'), ('.webm', 'webm')], default='.webm', max_length=200),
        ),
    ]
