# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadsource', '0012_video_storage_path_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_storage_path_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
