# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deadsource', '0013_video_preview_storage_path_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paginator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paginator_json', models.BinaryField(default='')),
                ('category', models.CharField(choices=[('Hot category', 'hot'), ('Adult category', 'adult'), ('Webm category', 'webm'), ('Mp4 category', 'mp4'), ('Category notset', 'notset')], default='Category notset', max_length=200)),
            ],
        ),
    ]
