# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadsource', '0014_paginator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paginator',
            new_name='PaginatorModel',
        ),
    ]
