# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadsource', '0018_auto_20171224_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_likes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_views',
        ),
        migrations.DeleteModel(
            name='VideoLike',
        ),
        migrations.DeleteModel(
            name='VideoView',
        ),
    ]
