# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadsource', '0020_auto_20171224_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoLike',
            new_name='VideoLikes',
        ),
        migrations.RenameModel(
            old_name='VideoView',
            new_name='VideoViews',
        ),
    ]
