# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadsource', '0021_auto_20171224_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadsource.VideoLikes'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_views',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deadsource.VideoViews'),
        ),
    ]
